<template>
  <nav class="grid grid-cols-2 md:grid-cols-4 gap-y-12 uppercase">
    <div class="space-y-12">
      <div>
        <HeadingSans>
          2023
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="against-filet"
              to="/against-filet"
            >
              Against Filet
              <Tag
                class="ml-2"
                color="bg-fuchsia-500"
              >
                New
              </Tag>
            </NavigationLink>
          </li>
        </ul>
      </div>
      <div>
        <HeadingSans>
          2022
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="lunchrider-exe"
              to="/lunchrider-exe"
            >
              LunchRider.exe
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          2021
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="ijwgh"
              to="/ijwgh"
            >
              I.J.W.G.H
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="28kbps"
              to="/28kbps"
            >
              28kbps
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="56kbps"
              to="/56kbps"
            >
              56kbps
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="untitled"
              to="/untitled"
            >
              Untitled
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="nief"
              to="/nief"
            >
              NIEF
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          2020
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="vazio"
              to="/vazio"
            >
              VAZIØ
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="vingt-vingt"
              to="/vingt-vingt"
            >
              VINGT-VINGT
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="moshaxe"
              to="/moshaxe"
            >
              MOSHAXÉ
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="triceracough"
              to="/triceracough"
            >
              TRICERACOUGH
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="fein"
              to="/fein"
            >
              FEIN
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          Archive
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="v3"
              to="/v3"
            >
              Version Three
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="v2"
              to="/v2"
            >
              Version Two
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-fuchsia-500"
              id="v1"
              to="/v1"
            >
              Version One
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>
